### PR TITLE
Add API to get storage usage and quota

### PR DESCRIPTION
**Pull request by TranceLove**
## Summary
Adds support to get the total file size at specified storage provider.

## Checklist:
- [ ] Documentation is up to date to reflect these changes
- [x] Created Unit tests

### CODE REVIEW

**Comment by TranceLove** [comment]
PR is ready for review :pray: do let me know if any documentation needs updating.

**Comment by TranceLove** [comment]
The failure at assembling modules for storage-sample app is caused by missing credentials required at `BuildConfig`, which the values are not supposed to exist at the repo. Anything I can do to work around this?

**Comment by dzuluaga** [comment]
Hey @adamTrz Any clue what's missing here? It look like the GH Action isn't picking up the local.properties file. 

CC - @Nataliagros 

```
> Task :apps:storage-sample:checkDebugDuplicateClasses
/home/runner/work/android-omh-storage/android-omh-storage/apps/storage-sample/build/generated/source/buildConfig/debug/com/openmobilehub/android/storage/sample/BuildConfig.java:12: error: illegal start of expression

> Task :apps:storage-sample:kaptDebugKotlin FAILED
  public static final String DROPBOX_CLIENT_ID = ;
                                                 ^
/home/runner/work/android-omh-storage/android-omh-storage/apps/storage-sample/build/generated/source/buildConfig/debug/com/openmobilehub/android/storage/sample/BuildConfig.java:13: error: illegal start of expression
  public static final String GOOGLE_CLIENT_ID = ;
                                                ^
/home/runner/work/android-omh-storage/android-omh-storage/apps/storage-sample/build/generated/source/buildConfig/debug/com/openmobilehub/android/storage/sample/BuildConfig.java:14: error: illegal start of expression
  public static final String MICROSOFT_CLIENT_ID = ;
                                                   ^
/home/runner/work/android-omh-storage/android-omh-storage/apps/storage-sample/build/generated/source/buildConfig/debug/com/openmobilehub/android/storage/sample/BuildConfig.java:15: error: illegal start of expression
  public static final String MICROSOFT_SIGNATURE_HASH = ;
```

**Comment by adamTrz** [comment]
> Hey @adamTrz Any clue what's missing here? It look like the GH Action isn't picking up the local.properties file.
> 

Hey @dzuluaga -  I think those values can not be empty strings. Gradle don't like that...

**Comment by adamTrz** [comment]
> Hey @adamTrz Any clue what's missing here? It look like the GH Action isn't picking up the local.properties file.
> 

That's strange - all those secrets should be populated during `Setup Secrets` GH Action Step

@TranceLove - mind resolving merge conflicts and trying to push changes again so we can trigger a new GH Actions run?

**Comment by TranceLove** [comment]
Yes sure. Along with #88 :pray:

**Comment by TranceLove** [comment]
@adamTrz seems I don't have write permission to push my branch here. May you help?

**Comment by adamTrz** [comment]
@TranceLove  I've granted you write access 👍 

@dzuluaga could you please check repo's / omh GH organization rules so everyone would be able to make contributions?

**Comment by dzuluaga** [comment]
@adamTrz granting write access to the repo isn’t recommended as it could expose sensitive information like secrets to external contributors. Instead, we should use manual approval with GitHub Environments.

This allows PRs to be reviewed, and after approval, workflows can safely access secrets (e.g., for APK generation). We can set up an environment (e.g., testing) that requires approval from a maintainer before running. More details can be found [here](https://docs.github.com/en/actions/deployment/using-environments-for-deployment#required-reviews).

Would you be able to set this up for the repos? Thanks!

CC - @Nataliagros

**Pull request closed without merging**
